import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { UnsupportedChainIdError, useWeb3React } from '@web3-react/core'
import { connector } from '../config/web3'
import { useCallback, useEffect, useState } from 'react'
import useTruncatedAddress from '../hooks/useTruncatedAddress'

const Home: NextPage = () => {
  const [balance, setBalance] = useState('')
  const { active, activate, account, deactivate, library, error } = useWeb3React()

  const isUnsupportedChain = error instanceof UnsupportedChainIdError

  const connect = useCallback(() => {
    activate(connector)
    localStorage.setItem('PreviouslyConnected', 'true')
  }, [activate])

  const disconnect = () => {
    deactivate()
    localStorage.removeItem('PreviouslyConnected')
  }

  const getBalance = useCallback(async () => {
    const toSet = await library.eth.getBalance(account)
    setBalance((toSet / 1e18).toFixed(2))
  }, [library?.eth, account])

  useEffect(() => {
    if (active) getBalance()
  }, [active, getBalance])

  useEffect(() => {
    if (localStorage.getItem('PreviouslyConnected') === 'true') connect()
  }, [connect])

  const truncatedAddress = useTruncatedAddress(account)

  return (
    <div className={styles.container}>
      <Head>
        <title>Survey App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Survey APP
        </h1>

        <div className={styles.grid}>
          {active
            ? (
              <div>
               <span>Address:  {truncatedAddress}</span>
               <span>Balance:  {balance}</span>
               <button onClick={disconnect}>Desconnect</button>
              </div>
              )
            : (
              <div>
                <span>Wallet desconectado</span>
                <button disabled={isUnsupportedChain} onClick={connect}> {isUnsupportedChain ? 'Red no soportada' : 'Conectar wallet'}</button>
              </div>
              )
          }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
